server:
  port: 8080
  ssl:
    key-store: classpath:www.lizhanfeng.xyz.jks
    key-store-password: 4ok86us6853608

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://116.62.126.94:7777/chinese_catering_culture?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1woshifanyu

      # 设置最大连接数，默认 100
      max-active: 20
      # 设置最小空闲连接数，默认 8
      min-idle: 5
      # 设置初始化连接数，默认 8
      initial-size: 10
      # 设置访问数据库时，最长等待时间，单位：毫秒，默认 30000
      max-wait: 10000
  redis:
    host: 116.62.126.94
    port: 6379
    password: 1woshifanyu
    jedis:
      pool:
        # 设置最大连接数，默认 8
        max-active: 32
        # 设置最大空闲连接数，默认8
        max-idle: 16
        # 设置最长等待时间，默认 -1，表示永不超时，时间太长会报连接异常
        max-wait: 300
        # 设置最小空闲连接数
        min-idle: 8
        time-between-eviction-runs: 5
    timeout: 86400
    database: 0

logging:
  file:
    name: log/warn.log
  level:
    com.inet: warn